# -*- coding: utf-8 -*-
"""
Created on Wed Apr  1 22:50:30 2026

@author: bingbing & baobao
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import rasterio
from rasterio.transform import from_origin
from matplotlib.colors import ListedColormap
import pylandstats as pls
from skimage import measure
from scipy.ndimage import binary_fill_holes

def rasterize_cluster_map(
    adata,
    cluster_col,
    coord_key='spatial',
    pixel_size=5.0,
    Image_col="IMAGE_ID",
    sample_id=None,
    output_tif=None,
    plot=True,
    random_seed=42,
    palette=None
):
    """
    Rasterize cell cluster labels into a 2D image based on spatial coordinates.

    This function converts single-cell spatial cluster assignments into a raster grid,
    where each pixel is assigned a cluster label based on the cells falling into that pixel.

    If multiple cells fall into the same pixel:
    - the majority label is used
    - ties are broken randomly using ``random_seed``

    Parameters
    ----------
    adata : anndata.AnnData
        AnnData object containing spatial coordinates and cluster labels.
    cluster_col : str
        Column in ``adata.obs`` storing cluster labels.
    coord_key : str, default='spatial'
        Key in ``adata.obsm`` storing spatial coordinates.
    pixel_size : float, default=5.0
        Pixel size used for rasterization.
    Image_col : str, default='IMAGE_ID'
        Column in ``adata.obs`` storing sample IDs.
    sample_id : str or None, default=None
        If provided, rasterize only this sample. Otherwise rasterize all cells in ``adata``.
    output_tif : str or None, default=None
        Output path for saving the GeoTIFF raster.
    plot : bool, default=True
        Whether to visualize the raster image.
    random_seed : int, default=42
        Random seed used to break ties when multiple labels are equally frequent within one pixel.
    palette : dict or None, default=None
        Custom color mapping for cluster labels.
        Keys should be strings of cluster labels, e.g. ``'0'``, ``'1'``.
        If None, the built-in default palette is used.

    Returns
    -------
    raster : numpy.ndarray
        Rasterized 2D label array.
    transform : affine.Affine
        Raster transform generated by ``rasterio.transform.from_origin``.

    Examples
    --------
    >>> custom_palette = {
    ...     '0': '#CC9900',
    ...     '1': '#BEBADA',
    ...     '2': '#8DD3C7'
    ... }
    >>>
    >>> raster, transform = rasterize_cluster_map(
    ...     adata=adata,
    ...     cluster_col='Spatial_Structure_cluster_scale_125',
    ...     coord_key='spatial',
    ...     pixel_size=10.0,
    ...     Image_col='IMAGE_ID',
    ...     sample_id='T009_ROI001',
    ...     output_tif='./T009_ROI001_scale125.tif',
    ...     plot=True,
    ...     palette=custom_palette
    ... )
    """
    if sample_id is not None:
        adata_sub = adata[adata.obs[Image_col] == sample_id]
    else:
        adata_sub = adata

    coords = np.asarray(adata_sub.obsm[coord_key])
    labels = adata_sub.obs[cluster_col].astype(int).values

    x_min, y_min = coords.min(axis=0)
    x_max, y_max = coords.max(axis=0)

    width = int(np.ceil((x_max - x_min) / pixel_size))
    height = int(np.ceil((y_max - y_min) / pixel_size))

    pixel_labels = [[[] for _ in range(width)] for _ in range(height)]
    raster = np.full((height, width), -1, dtype=np.int32)

    np.random.seed(random_seed)

    px = ((coords[:, 0] - x_min) / pixel_size).astype(int)
    py = ((coords[:, 1] - y_min) / pixel_size).astype(int)
    py = height - 1 - py

    for x, y, lab in zip(px, py, labels):
        if 0 <= x < width and 0 <= y < height:
            pixel_labels[y][x].append(lab)

    for y in range(height):
        for x in range(width):
            cell_labels = pixel_labels[y][x]
            if len(cell_labels) == 0:
                raster[y, x] = -1
            elif len(cell_labels) == 1:
                raster[y, x] = cell_labels[0]
            else:
                unique_labels, counts = np.unique(cell_labels, return_counts=True)
                max_count = np.max(counts)
                modes = unique_labels[counts == max_count]

                if len(modes) == 1:
                    raster[y, x] = modes[0]
                else:
                    raster[y, x] = np.random.choice(modes)

    transform = from_origin(x_min, y_max, pixel_size, pixel_size)

    if output_tif:
        with rasterio.open(
            output_tif, 'w',
            driver='GTiff', height=height, width=width,
            count=1, dtype=raster.dtype,
            crs='+proj=utm +zone=33 +datum=WGS84',
            transform=transform
        ) as dst:
            dst.write(raster, 1)
        print(f"Saved raster to: {output_tif}")

    if plot:
        plt.figure(figsize=(8, 8))

        if palette is None:
            palette = {
                '0': '#CC9900', '1': "#BEBADA", '2': "#8DD3C7",
                '3': "#BC80BD", '4': "#FB8072", '5': "#80B1D3",
                '6': "#FCCDE5", '7': '#FFD121', '8': "#FDB462",
                '9': "#FFFFB3", '10': '#7CC767', '11': "#E5C494",
                '12': "#D8D155", '13': "#B3DE69", '14': "#C1E6F3",
                '15': '#f5dbd3', '16': '#ABA09C', '17': "#D9D9D9",
                '18': "#D4A6C8", '19': "#D4E1A2"
            }

        display_raster = raster.copy().astype(float)
        unique_labels = np.unique(raster[raster != -1])
        unique_labels = np.sort(unique_labels)

        colors = ['#000000']
        for label in unique_labels:
            colors.append(palette.get(str(label), '#808080'))

        cmap = ListedColormap(colors)

        norm_display_raster = display_raster.copy()
        norm_display_raster[display_raster == -1] = 0

        for idx, label in enumerate(unique_labels, 1):
            norm_display_raster[display_raster == label] = idx

        plt.imshow(norm_display_raster, cmap=cmap, vmin=0, vmax=len(unique_labels))

        image_id = adata_sub.obs[Image_col].iloc[0] if Image_col in adata_sub.obs.columns else 'Unknown'
        plt.title(image_id, fontname='Arial', fontsize=60, fontweight='bold', ha='center', pad=20)
        plt.axis('off')
        plt.tight_layout()

        if output_tif:
            base_name = os.path.splitext(output_tif)[0]
            image_filename = f"{base_name}_plot.png"
            plt.savefig(image_filename, dpi=300, bbox_inches='tight', facecolor='white')
            print(f"Saved plot to: {image_filename}")

        plt.show()

    return raster, transform


def run_landscape_metric_analysis(
    adata,
    cluster_cols,
    Image_col='IMAGE_ID',
    pixel_size=10.0,
    output_dir='./raster_results/',
    coord_key='spatial',
    palette=None,
    landscape_metrics=None,
    class_metrics=None,
    plot=True
):
    """
    Rasterize cell clusters for each sample and scale, then compute landscape-level
    and class-level spatial metrics using pylandstats.

    Workflow
    --------
    1. Rasterize cluster labels for each sample and scale.
    2. Convert the raster into a ``pylandstats.Landscape`` object.
    3. Compute landscape-level metrics.
    4. Compute class-level metrics.
    5. Save per-sample outputs and return combined DataFrames.

    Parameters
    ----------
    adata : anndata.AnnData
        AnnData object containing clustering results and spatial coordinates.
    cluster_cols : list of str
        Cluster columns to process, typically one column per scale.
        Example:
        ``['Spatial_Structure_cluster_scale_8',
           'Spatial_Structure_cluster_scale_19']``
    Image_col : str, default='IMAGE_ID'
        Column in ``adata.obs`` storing sample IDs.
    pixel_size : float, default=10.0
        Pixel size used during rasterization.
    output_dir : str, default='./raster_results/'
        Output directory for TIFF files, plots, and metric CSV files.
    coord_key : str, default='spatial'
        Key in ``adata.obsm`` storing spatial coordinates.
    palette : dict or None, default=None
        Custom cluster color mapping passed to ``rasterize_cluster_map``.
    landscape_metrics : list of str or None, default=None
        Landscape-level metric names passed to ``compute_landscape_metrics_df``.
        If None, a default SpaScope metric list is used.
    class_metrics : list of str or None, default=None
        Class-level metric names passed to ``compute_class_metrics_df``.
        If None, a default SpaScope metric list is used.
    plot : bool, default=True
        Whether to plot raster images during processing.

    Returns
    -------
    all_landscape_df : pandas.DataFrame
        Combined landscape-level metrics across all samples and scales.
    all_class_df : pandas.DataFrame
        Combined class-level metrics across all samples and scales.

    Examples
    --------
    >>> landscape_metric_list = [
    ...     'total_area',
    ...     'number_of_patches',
    ...     'patch_density',
    ...     'largest_patch_index',
    ...     'entropy',
    ...     'shannon_diversity_index',
    ...     'contagion'
    ... ]
    >>>
    >>> class_metric_list = [
    ...     'total_area',
    ...     'proportion_of_landscape',
    ...     'number_of_patches',
    ...     'patch_density',
    ...     'largest_patch_index'
    ... ]
    >>>
    >>> all_landscape_df, all_class_df = run_landscape_metric_analysis(
    ...     adata=adata,
    ...     cluster_cols=[
    ...         'Spatial_Structure_cluster_scale_8',
    ...         'Spatial_Structure_cluster_scale_19',
    ...         'Spatial_Structure_cluster_scale_44',
    ...         'Spatial_Structure_cluster_scale_125'
    ...     ],
    ...     Image_col='IMAGE_ID',
    ...     pixel_size=10.0,
    ...     output_dir='./raster_results/',
    ...     palette=None,
    ...     landscape_metrics=landscape_metric_list,
    ...     class_metrics=class_metric_list,
    ...     plot=True
    ... )
    """
    if landscape_metrics is None:
        landscape_metrics = [
            'total_area',
            'number_of_patches',
            'patch_density',
            'largest_patch_index',
            'total_edge',
            'edge_density',
            'total_core_area',
            'number_of_disjunct_core_areas',
            'landscape_shape_index',
            'effective_mesh_size',
            'entropy',
            'shannon_diversity_index',
            'joint_entropy',
            'conditional_entropy',
            'mutual_information',
            'relative_mutual_information',
            'contagion'
        ]

    if class_metrics is None:
        class_metrics = [
            'total_area',
            'proportion_of_landscape',
            'number_of_patches',
            'patch_density',
            'largest_patch_index',
            'total_edge',
            'edge_density',
            'total_core_area',
            'core_area_proportion_of_landscape',
            'number_of_disjunct_core_areas',
            'landscape_shape_index',
            'effective_mesh_size'
        ]

    all_landscape_metrics = []
    all_class_metrics = []

    sample_ids = adata.obs[Image_col].unique()

    for cluster_col in cluster_cols:
        scale_str = cluster_col.split('_')[-1].replace('.0', '')
        scale_dir = os.path.join(output_dir, f'scale_{scale_str}')
        os.makedirs(scale_dir, exist_ok=True)
        print(f"\n===== Processing scale {scale_str} =====")

        for sid in sample_ids:
            print(f"▶ Sample: {sid}")

            tif_path = os.path.join(scale_dir, f"{sid}_scale{scale_str}.tif")
            raster, transform = rasterize_cluster_map(
                adata=adata,
                cluster_col=cluster_col,
                coord_key=coord_key,
                sample_id=sid,
                Image_col=Image_col,
                pixel_size=pixel_size,
                output_tif=tif_path,
                plot=plot,
                palette=palette
            )

            with rasterio.open(tif_path) as src:
                raster = src.read(1)
                transform = src.transform
                res_x = transform[0]
                res_y = -transform[4]

            raster[raster >= 0] += 1
            raster[raster < 0] = 0

            landscape = pls.Landscape(raster, res=(res_x, res_y), background=0)

            landscape_metrics_df = landscape.compute_landscape_metrics_df(metrics=landscape_metrics)
            landscape_metrics_df['IMAGE_ID'] = sid
            landscape_metrics_df['scale'] = scale_str
            landscape_metrics_df['cluster_col'] = cluster_col
            all_landscape_metrics.append(landscape_metrics_df)

            class_metrics_df = landscape.compute_class_metrics_df(metrics=class_metrics)
            class_metrics_df['IMAGE_ID'] = sid
            class_metrics_df['scale'] = scale_str
            class_metrics_df['cluster_col'] = cluster_col
            all_class_metrics.append(class_metrics_df)

            csv_l = os.path.join(scale_dir, f"{sid}_scale{scale_str}_LANDSCAPE_metrics.csv")
            csv_c = os.path.join(scale_dir, f"{sid}_scale{scale_str}_CLASS_metrics.csv")

            landscape_metrics_df.to_csv(csv_l, index=True)
            class_metrics_df.to_csv(csv_c, index=True)

            print(f"   Saved landscape metrics: {csv_l}")
            print(f"   Saved class metrics:      {csv_c}")

    all_landscape_df = pd.concat(all_landscape_metrics, ignore_index=False)
    all_class_df = pd.concat(all_class_metrics, ignore_index=False)

    all_landscape_df.to_csv(os.path.join(output_dir, "ALL_samples_ALL_scales_LANDSCAPE_metrics.csv"), index=True)
    all_class_df.to_csv(os.path.join(output_dir, "ALL_samples_ALL_scales_CLASS_metrics.csv"), index=True)

    print("\nALL metrics saved to output directory")

    return all_landscape_df, all_class_df


def plot_cluster_patches(
    adata,
    cluster_col,
    coord_key='spatial',
    pixel_size=5.0,
    Image_col='IMAGE_ID',
    sample_id=None,
    output_tif=None,
    plot=True,
    random_seed=42,
    palette=None
):
    """
    Rasterize cell clusters and visualize patch structures with explicit patch boundaries.

    Compared with standard raster plotting, it further identifies connected regions
    (patches) for each cluster and draws their boundaries.

    Parameters
    ----------
    adata : anndata.AnnData
        AnnData object containing spatial coordinates and cluster labels.
    cluster_col : str
        Column in ``adata.obs`` storing cluster labels.
    coord_key : str, default='spatial'
        Key in ``adata.obsm`` storing spatial coordinates.
    pixel_size : float, default=5.0
        Pixel size used for rasterization.
    Image_col : str, default='IMAGE_ID'
        Column in ``adata.obs`` storing sample IDs.
    sample_id : str or None, default=None
        If provided, only rasterize and plot this sample.
    output_tif : str or None, default=None
        Output path for saving the TIFF raster.
    plot : bool, default=True
        Whether to display and save the patch plot.
    random_seed : int, default=42
        Random seed used when ties occur within a pixel.
    palette : dict or None, default=None
        Custom color mapping for cluster labels.
        Keys should be strings of cluster labels, e.g. ``'0'``, ``'1'``.

    Returns
    -------
    raster : numpy.ndarray
        Rasterized 2D label array.
    transform : affine.Affine
        Raster transform for the output TIFF.

    Examples
    --------
    >>> raster, transform = plot_cluster_patches(
    ...     adata=adata,
    ...     cluster_col='Spatial_Structure_cluster_scale_125',
    ...     coord_key='spatial',
    ...     pixel_size=10.0,
    ...     Image_col='IMAGE_ID',
    ...     sample_id='T009_ROI001',
    ...     output_tif='./T009_ROI001_scale125_color_patch_pixel.tif',
    ...     plot=True,
    ...     palette=None
    ... )
    """
    if sample_id is not None:
        adata_sub = adata[adata.obs[Image_col] == sample_id]
    else:
        adata_sub = adata

    coords = np.asarray(adata_sub.obsm[coord_key])
    labels = adata_sub.obs[cluster_col].astype(int).values

    x_min, y_min = coords.min(axis=0)
    x_max, y_max = coords.max(axis=0)

    width = int(np.ceil((x_max - x_min) / pixel_size))
    height = int(np.ceil((y_max - y_min) / pixel_size))

    pixel_labels = [[[] for _ in range(width)] for _ in range(height)]
    raster = np.full((height, width), -1, dtype=np.int32)

    np.random.seed(random_seed)

    px = ((coords[:, 0] - x_min) / pixel_size).astype(int)
    py = ((coords[:, 1] - y_min) / pixel_size).astype(int)
    py = height - 1 - py

    for x, y, lab in zip(px, py, labels):
        if 0 <= x < width and 0 <= y < height:
            pixel_labels[y][x].append(lab)

    for y in range(height):
        for x in range(width):
            cell_labels = pixel_labels[y][x]
            if len(cell_labels) == 0:
                raster[y, x] = -1
            elif len(cell_labels) == 1:
                raster[y, x] = cell_labels[0]
            else:
                unique_labels, counts = np.unique(cell_labels, return_counts=True)
                max_count = np.max(counts)
                modes = unique_labels[counts == max_count]
                raster[y, x] = modes[0] if len(modes) == 1 else np.random.choice(modes)

    transform = from_origin(x_min, y_max, pixel_size, pixel_size)

    if output_tif:
        with rasterio.open(
            output_tif, 'w',
            driver='GTiff', height=height, width=width,
            count=1, dtype=raster.dtype,
            crs='+proj=utm +zone=33 +datum=WGS84',
            transform=transform
        ) as dst:
            dst.write(raster, 1)
        print(f"Saved raster to: {output_tif}")

    if plot:
        if palette is None:
            palette = {
                '0': '#CC9900', '1': "#BEBADA", '2': "#8DD3C7",
                '3': "#BC80BD", '4': "#FB8072", '5': "#80B1D3",
                '6': "#FCCDE5", '7': '#FFD121', '8': "#FDB462",
                '9': "#FFFFB3", '10': '#7CC767', '11': "#E5C494",
                '12': "#D8D155", '13': "#B3DE69", '14': "#C1E6F3",
                '15': '#f5dbd3', '16': '#ABA09C', '17': "#D9D9D9",
                '18': "#D4A6C8", '19': "#D4E1A2"
            }

        unique_labels = np.unique(raster[raster != -1])
        unique_labels = np.sort(unique_labels)

        cmap = ListedColormap(['#000000'])
        display_raster = raster.copy().astype(float)
        display_raster[display_raster == -1] = 0
        for idx, cluster_label in enumerate(unique_labels, 1):
            display_raster[raster == cluster_label] = idx

        fig, ax = plt.subplots(figsize=(8, 8))
        ax.imshow(display_raster, cmap=cmap, vmin=0, vmax=len(unique_labels),
                  origin='upper', extent=[0, width, height, 0])
        ax.set_axis_off()

        for y_pix in range(height):
            for x_pix in range(width):
                label = raster[y_pix, x_pix]
                if label == -1:
                    continue
                color = palette.get(str(label), '#FFFFFF')
                ax.plot([x_pix, x_pix+1], [y_pix, y_pix+1], color=color, linewidth=2)

        for cluster_label in unique_labels:
            mask = (raster == cluster_label)
            filled = binary_fill_holes(mask)
            labeled = measure.label(filled, connectivity=1)
            color = palette.get(str(cluster_label), '#FFFFFF')

            for region_idx in np.unique(labeled):
                if region_idx == 0:
                    continue
                region_mask = (labeled == region_idx)
                ys, xs = np.where(region_mask)

                edges = set()
                for y_pix, x_pix in zip(ys, xs):
                    if y_pix == 0 or not region_mask[y_pix-1, x_pix]:
                        edges.add(((x_pix, y_pix), (x_pix+1, y_pix)))
                    if y_pix == region_mask.shape[0]-1 or not region_mask[y_pix+1, x_pix]:
                        edges.add(((x_pix, y_pix+1), (x_pix+1, y_pix+1)))
                    if x_pix == 0 or not region_mask[y_pix, x_pix-1]:
                        edges.add(((x_pix, y_pix), (x_pix, y_pix+1)))
                    if x_pix == region_mask.shape[1]-1 or not region_mask[y_pix, x_pix+1]:
                        edges.add(((x_pix+1, y_pix), (x_pix+1, y_pix+1)))
                for (x0, y0), (x1, y1) in edges:
                    ax.plot([x0, x1], [y0, y1], color=color, linewidth=2)

        sample_name = adata_sub.obs[Image_col].iloc[0] if Image_col in adata_sub.obs.columns else 'Unknown'
        plt.title(sample_name, fontsize=48, fontweight='bold', fontname='Arial', pad=20)
        plt.tight_layout()

        if output_tif:
            base_name = os.path.splitext(output_tif)[0]
            png_path = f"{base_name}_per_pixel_diag_final.png"
            plt.savefig(png_path, dpi=300, bbox_inches='tight', facecolor='white')
            print(f"✅ Saved PNG with per-pixel diagonal lines: {png_path}")

        plt.show()

    return raster, transform

